name: Docker Image Builder

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
        with:
            push: true
            tags: |
                ${{ secrets.DOCKERHUB_LOGIN }}/${{ secrets.DOCKERHUB_IMAGE }}:$(date +%Y%m%d%H%M%S)
