name: Docker Image Builder

on:
  repository_dispatch:
    types: [Docker Image Builder]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}
      DOCKER_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}
    - name: Build and push
      run: chmod +x dockerize.sh; ./dockerize.sh $DOCKER_LOGIN $DOCKER_PASSWORD $DOCKER_IMAGE
