name: Docker Image Builder

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      run: chmod +x dockerize.sh; ./dockerize.sh
